"""
break statement executes inside a loop, control flow breaks out of the loop immediately; note that break statements are allowed inside loops, syntatically.
continue statement will skip to the next iteration of the loop bypassing rest of the current block; as with break continue can only appear inside loops

Python doesn't have the ability to break out of multiple levels at once. if this behaviour is desired refactoring one or more loops into a function and replacing break with return maybe the way to go.
"""


